version: "3.3"

services:
  parity-node:
    image: "parity/parity:latest"
    volumes:
      - ${EXISTING_PARITY_BASE_PATH:-parity-data}:/parity-data
    working_dir: /parity-data
    command: ["--base-path=/parity-data", 
              "--jsonrpc-port=58545", 
              "--jsonrpc-interface=all",
              "--jsonrpc-hosts=all",
              "--jsonrpc-cors=all",
              "--jsonrpc-threads=20"]
    ports: 
      - "58545:58545"

  # geth-node:
  #   image: "ethereum/client-go:latest"
  #   volumes:
  #     - geth-data:/geth
  #   working_dir: /geth
  #   command: ["--syncmode", "fast", "--cache", "4096"]
  
  ethdash:
    build: .
    environment:
      - WEB3_PROVIDER_URI=file:///parity-data/jsonrpc.ipc
    volumes:
      - ${EXISTING_PARITY_BASE_PATH:-parity-data}:/parity-data
    command: ["python", "-W", "ignore", "-m", "ethdash.main"]
    stdin_open: true
    tty: true
    depends_on: 
      - parity-node


volumes:
  parity-data:
  # geth-data: